### ISSUE TITLE
Tracebacks with Ventura / M1

### ISSUE THREAD

**Issue by CBBuerger** [munkireport/usage_stats#3]
Running usage_stats
    usage_stats Error: Traceback (most recent call last):
  File "/usr/local/munkireport/scripts/usage_stats", line 197, in <module>
    main()
  File "/usr/local/munkireport/scripts/usage_stats", line 188, in main
    info = get_usage_metrics()
  File "/usr/local/munkireport/scripts/usage_stats", line 12, in get_usage_metrics
    plist = plistlib.readPlistFromString(output.rstrip(' \t\r\n\0'))
  File "/Library/MunkiReport/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 103, in readPlistFromString
    return readPlist(StringIO(data))
  File "/Library/MunkiReport/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 78, in readPlist
    rootObject = p.parse(pathOrFile)
  File "/Library/MunkiReport/Python.framework/Versions/2.7/lib/python2.7/plistlib.py", line 406, in parse
    parser.ParseFile(fileobj)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 11680, column 33
WARNING: usage_stats return code: 1

**Comment by flammable** [comment]
Just to clarify - where are you seeing this message? When running `/usr/local/munkireport/munkireport-runner` manually?

I'm running Ventura on an Intel Mac and not seeing this output, so it might just be an Apple Silicon thing.

**Comment by CBBuerger** [comment]
Hi
at the moment I'm seeing this on two intel macbooks running 13.2

**Comment by tuxudo** [comment]
Is this still an issue with the latest version of the module?
